### ISSUE TITLE
PHP version constraint

### ISSUE THREAD

**Issue by DL1ndner** [fnagel/pluploadfe#25]
composer.json mentions PHP version "^8.2" as dependency, but ext_emconf.php and release note says PHP 8.3.
Could you pls. update composer.json?

**Comment by fnagel** [comment]
Ohhh, good catch! Would you mind to test this real quick so I sure the constraints are correct now before I publish a hotfix release?

Just use `"felixnagel/pluploadfe": "dev-master"` in your compsoer file. Thanks!

**Comment by DL1ndner** [comment]
Hi and Thanks! Works as expected :-)

**Comment by fnagel** [comment]
@DL1ndner  Sorry, for bothering again, but what was exactly the issue here? Did you ran into problems when installing v8.0.0 on a PHP 8.3 installation? Or anything else?

I've did some actual testing in an PHP 8.3 environment and using `^8.2` allows PHP 8.3 as well (as intended). 
So I don't see an actual issue here.

**Comment by DL1ndner** [comment]
Oops! I think you're right. I ran into an issue by trying to update from 7.0 to 8.0 on PHP 8.3. So I checked if there is a problem with your composer.json and just quickly saw "8.2". 

Investigating further the problem, I could find that the problem was on my side - having a config.platfom.php = 8.2.1 setting in my project composer.json. 

Sorry for bothering you ...

**Comment by fnagel** [comment]
All good. Glad we figured it out :-) 
Have a nice weekend!
