### ISSUE TITLE
Scripts only on the plugin page?!

### ISSUE THREAD

**Issue by Gorli** [fnagel/pluploadfe#4]
Hello!
Is it possible or even better if all scripts and CSS files are loaded only on the plugin page. Currently the files to be loaded on all sites when the plugin is installed. Also on the sites where the plug is not used. In the file "class.tx_pluploadfe_pi1.php" I tentatively tried following that worked well. What do you think about it?

```
use TYPO3\CMS\Core\Page\PageRenderer;
...
protected function renderCode() {
...
protected function renderCode() {
...
    $pageRenderer = GeneralUtility::makeInstance(PageRenderer::class);

    $CssFile = 'EXT:pluploadfe/res/plupload/js/jquery.plupload.queue/css/jquery.plupload.queue.css';
    $CssFile = $GLOBALS['TSFE']->tmpl->getFileName($CssFile);      
    $pageRenderer->addCssFile($CssFile);          

    $jsFooterFile1 = 'EXT:pluploadfe/res/plupload/js/plupload.full.min.js';
    $jsFooterFile1 = $GLOBALS['TSFE']->tmpl->getFileName($jsFooterFile1);
    $pageRenderer->addJsFooterFile($jsFooterFile1);

    $jsFooterFile2 = 'EXT:pluploadfe/res/plupload/js/jquery.plupload.queue/jquery.plupload.queue.min.js';
    $jsFooterFile2 = $GLOBALS['TSFE']->tmpl->getFileName($jsFooterFile2);
    $pageRenderer->addJsFooterFile($jsFooterFile2);     
}
```

Thank you very much

Goarli

**Comment by fnagel** [comment]
It's possible using PHP within the controller actions like you proposed. And it seems like a good idea when using a simple frontend setup, as the files will only be included when the plugin is actually used on a page. Sounds good right? 

Not really, because as soon as you add compressing and minifying you will end up with quite a bunch of similar but hardly the same combined JS files. 
Let's say you have three plugins adding JS when needed. Page A has plugin A and B, Page B has only Plugin B and Page C contains Plugin A and C. This way you will end up with a file for A and B, a file for B only, a file for A and C plugin -- each one needs to be downloaded by the user, even if the needed JS is already available on the client!

That's why I prefer flexible integration by using TS for all my extensions. This way a integrator can decide to include the JS on every page or specific sections of a website, include it in merging and compressing or not, where in the DOM (using includeJS, includeJSFooterlibs or includeJSFooter) or even don't use the provided scripts at all. Sounds reasonable?

**Comment by Gorli** [comment]
Hello,

Thanks for the quick reply!

Your thoughts approach is a view which I have to respect and understand. It remains each themselves left as he manages the scripts or sets available. I do not use your plugin on public pages. Therefore my solution is the better way for me and I will spare others a longer charging time.

Thanks anyway :-)

Goarli
